# Generated by Django 4.2.6 on 2023-10-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_remove_usuario_usuario_administrador_usuario_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='usuario',
            name='usuario_administrador',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario_tipo',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('operador', 'Operador'), ('administrador', 'Administrador')], default='cliente', max_length=15, verbose_name='Tipo de usuario'),
        ),
    ]
