# Generated by Django 4.2.6 on 2023-10-24 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_remove_usuario_username_usuario_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config_tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_config_tarifa', models.CharField(max_length=50)),
                ('desc_config_tarifa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conv_vigente', models.CharField(max_length=10)),
                ('num_meses', models.CharField(max_length=20)),
                ('cant_cuotas', models.CharField(max_length=25)),
                ('cuota_no_paga', models.CharField(max_length=25)),
                ('monto_a_pago', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='costo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total_costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insumo_costo', models.CharField(max_length=25)),
                ('gasto_opr_costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rrhh_costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('otro_costo', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montoneto_boleta', models.CharField(max_length=25)),
                ('iva_boleta', models.CharField(max_length=25)),
                ('total_boleta', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('monto_total', models.CharField(max_length=25)),
                ('estado', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ini_dpago', models.DateField()),
                ('fecha_fin_dpago', models.DateField()),
                ('monto_dpago', models.CharField(max_length=30)),
                ('metro_cubico', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Interes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_interes', models.CharField(max_length=30)),
                ('porcentaje_interes', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Registro_sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField()),
                ('accion', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Subsidio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_subsidio', models.CharField(max_length=30)),
                ('desc_subsidio', models.CharField(max_length=30)),
                ('porcentaje_subsidio', models.CharField(max_length=30)),
            ],
        ),
    ]
