# Generated by Django 4.2.6 on 2023-10-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_config_tarifa_convenio_costo_detalle_boleta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='numero_medidor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número de Medidor'),
        ),
    ]
